---
- name: devel | Install devel packages
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - go-compilers-golang-compiler
  - golang-bin
  - love
  - lua
  - lua-devel
  - openssl-devel
  - python3-pygments
  - python3-pygments-markdown-lexer
  - hugo
  - pipenv
  - git
  - rubygems
  - ruby-devel
  - levien-inconsolata-fonts
  - mozilla-fira-mono-fonts
  - mozilla-fira-sans-fonts
  - overpass-mono-fonts
  - overpass-fonts
  - gobby05
  - pandoc
  - tilix
  - pipenv
  - '@Fedora Packager'
  - '@RPM Development Tools'
  - '@C Development Tools and Libraries'

- name: devel | user devel dir | user dev_dir set-up
  file:
      dest: "{{ansible_user_dir}}/Code"
      owner: "{{home_dir_user}}"
      group: "{{home_dir_user}}"
      state: directory
