---
- name: devel | Install devel packages
  package:
      state: latest
      name: "{{ item }}"
  with_items:
  - go-compilers-golang-compiler
  - golang-bin
  - love
  - lua
  - python3-virtualenvwrapper
  - git
  - rubygems
  - ruby-devel

- name: devel | install pip v2 system packages
  pip:
      name: "{{ item }}"
  with_items:
    - cryptography
    - requests
    - xmltodict

- name: devel | install pip v3 system packages
  pip:
      name: "{{ item }}"
      executable: pip-3
  with_items:
    - cryptography
    - requests
    - xmltodict

- name: devel | Install devel fonts
  package:
      state: latest
      name: "{{ item }}"
  with_items:
  - google-droid-sans-mono-fonts
  - levien-inconsolata-fonts
  - mozilla-fira-mono-fonts
  - mozilla-fira-sans-fonts
  - overpass-mono-fonts
  - overpass-fonts

- name: devel | user devel dir | user dev_dir set-up
  file:
      dest: "{{ansible_user_dir}}/Code"
      owner: "{{ansible_user_id}}"
      group: "{{ansible_user_id}}"
      state: directory

- name: devel | IDE | set up IDE for devel
  copy:
    src: ZeroBraneStudioEduPack-1.60-linux.sh
    dest: "{{ansible_user_dir}}/Code"
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_id}}"
    mode: 0755

