---
- hosts: dumuzi.local
  remote_user: "{{ home_dir_user }}"
  tasks:
  - name: backup | archive specific dir dirs
    synchronize:
      src: "{{ ansible_user_dir }}"
      dest: "{{ ansible_user_dir }}/Backups/"
      archive: yes
      rsync_opts:
        - "--exclude=.mozilla"
        - "--exclude=.ccache"
        - "--exclude=.cache"
        - "--exclude=.VM"
        - "--exclude=.PlayOnLinux*"
        - "--exclude=.thunderbird"
        - "--exclude=.gnome*"
        - "--exclude=Sync"
    delegate_to: dumuzi.local
    
