---
- name: ansible-master | install Ansible
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
    - ansible
    - lynx
    - mutt
    - wget
    - vim
    - git

- name: ansible-master | Configure Ansible
  copy:
    src: ansible.cfg
    dest: /etc/ansible/ansible.cfg
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: ansible-master | Copy inventory
  copy:
    src: hosts
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: ansible-master | create ansible user
  user:
    name: ansible
    groups: wheel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_type: ecdsa

- name: ansible-master | copy .gitconfig
  copy:
    src: gitconfig
    dest: /home/ansible/.gitconfig
    owner: ansible
    group: ansible
    mode: 0644
   
- name: ansible-master | clone git
  git:
    repo: ssh://git@github.com:XakV/ChongoChingi.git
    dest: /home/ansible/

   
