---
- name: entertainment | set some directories
  file:
      dest: "{{ansible_user_dir}}/{{ item }}"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      state: directory
  with_items:
  - "Podcasts"
  - "Library"
