---
- name: Restic  | Install restic packages
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
  - restic
  - python3-scp
  - python3-paramiko
  - python3-dnf-plugins-extras-common
  - python3-dnf-plugins-core
  become: True

- name: copy cron.allow is important
  copy:
    src: cron.allow
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0644    
  become: True

  # name: init restic
  # command: 'restic -r /opt/backups init --password-file=/opt/backups/.restic_info'
 
- name: schedule backups
  cron:
    name: srv_backup
    hour: 01
    minute: 15
    weekday: "{{ item.dOw }}"
    job: "restic -r sftp:zach@192.168.0.215:/srv/bkup backup /home/zach/{{ item.folder }} --password-file=/home/zach/.restic_info"
  loop:
  - { 'dOw': '1', 'folder': '/home/zach/Documents' }
  - { 'dOw': '3', 'folder': '/home/zach/Music' }
  - { 'dOw': '5', 'folder': '/home/zach/Pictures' }
  notify:
  - reload cron

- name: prune daily backups
  cron:
    name: prune snapshots with restic
    weekday: 0
    hour: 23
    minute: 45
    job: restic -r sftp:zach@192.168.0.215:/srv/bkup forget --keep-last 10 keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune --password-file=/home/zach/.restic.info
