---
- name: Restic  | Install restic packages
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
  - restic
  - python3-scp
  - python3-paramiko
  - python3-dnf-plugins-extras-common
  - python3-dnf-plugins-core
  become: True

- name: Restic | make sure /srv exists and is owned by user
  file:
    path: /opt/backups
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: copy exclude file
  copy:
    src: restic_excludes.txt
    dest: /opt/backups/
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: copy restic pwd file
  copy:
    src: .restic_info
    dest: /opt/backups/
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: copy cron.allow is important
  copy:
    src: cron.allow
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0644    
  become: True

  # name: init restic
  # command: 'restic -r /opt/backups init --password-file=/opt/backups/.restic_info'
 
- name: schedule backups
  cron:
    name: srv_backup
    hour: 01
    minute: 15
    job: "restic -r /opt/backups backup /srv --exclude-file /opt/backups/restic_excludes --password-file=/opt/backups/.restic_info"
  notify:
  - reload cron

- name: prune daily backups
  cron:
    name: prune snapshots with restic
    weekday: 0
    hour: 23
    minute: 45
    job: restic -r /opt/backups forget --keep-last 10 keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune --password-file=/opt/backups/.restic_info 
