---
- name: nvidia | Install NVidia if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - dkms-nvidia
  - nvidia-driver
  - nvidia-driver-libs.i686
  - nvidia-driver-libs.x86_64
  - nvidia-settings
  - nvidia-libXNVCtrl
  - nvidia-settings
  - nvidia-modprobe
  - nvidia-xconfig
  - libglvnd
  - libglvnd-egl
  - libglvnd-gles
  - libglvnd-glx
  - libglvnd-opengl
  - libglvnd-core-devel
  - libglvnd-devel
  - libvdpau
  
- name: nvidia | block nouveau
  kernel_blacklist: 
    name: nouveau
    state: present

- name: nvidia | edit grub cmdline config
  lineinfile:
    path: /etc/sysconfig/grub
    regexp: '^GRUB_CMDLINE_LINUX'
    line: 'GRUB_CMDLINE_LINUX="rhgb quiet rd.blacklist.nouveau"'

- name: nvidia | update grub
  command: '/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg'
  when: bios_mach == true

- name: nvidia | update grub
  command: '/usr/sbin/grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg'
  when: bios_mach == false


- name: nvidia | dracut
  command: '/usr/bin/dracut /boot/initramfs-$(uname -r).img $(uname -r)'
