---
- name: gaming | install negativo repos
  yum_repository:
      name: fedora-nvidia
      description: negativo17 - Multimedia 
      baseurl: https://negativo17.org/repos/fedora-nvidia/fedora-$releasever/$basearch/
      gpgcheck: no
      enabled: yes
  notify: update-all

- name: nvidia | Install NVidia if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - dkms-nvidia
  - nvidia-driver
  - nvidia-driver-libs.i686
  - nvidia-driver-libs.x86_64
  - nvidia-settings
  - nvidia-xconfig
  - libglvnd
  - libglvnd-egl
  - libglvnd-gles
  - libglvnd-glx
  - libglvnd-opengl
  - libglvnd-core-devel
  - libglvnd-devel
  - libvdpau

