---
- name: nvidia | Install NVidia if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - xorg-x11-drv-nvidia.x86_64
  - nvidia-settings
  - nvidia-xconfig
  - nvidia-modprobe
  - xorg-x11-drv-nvidia-libs.i686

