---
- name: nvidia | Install NVidia if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - dkms-nvidia
  - nvidia-driver
  - nvidia-driver-libs.i686
  - nvidia-driver-libs.x86_64
  - nvidia-settings
  - nvidia-xconfig
  - libglvnd
  - libglvnd-egl
  - libglvnd-gles
  - libglvnd-glx
  - libglvnd-opengl
  - libglvnd-core-devel
  - libglvnd-devel
  - libvdpau

