- name: restart_iscsi
  systemd:
    name: iscsi 
    enabled: yes
    state: restarted
  systemd:
    name: iscsid
    enabled: yes
    state: restarted

- name: partition_device
  parted: 
    device: "{{ returned_device.devicenodes[0] }}"
    number: 1
    state: present
  register: partition_info
