- name: restart_iscsi
  systemd:
    name: iscsi 
    enabled: yes
    state: restarted
  systemd:
    name: iscsid
    enabled: yes
    state: restarted

- name: partition_and_mount
  parted: 
    device: "{{ * }}"
