---
- name: initiator | Install initiator packages
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - iscsi-initiator-utils
  become: yes
  become_user: root

- name: Copy a new initiatorname.iscsi file | back up original
  template:
    src: initiatorname.j2
    dest: /etc/iscsi/initiatorname.iscsi
    owner: root
    group: root
    mode: 0644
    backup: yes    
  notify: restart_iscsi
  become: yes
  become_user: root

- name: Create the mountpoint 
  file:
    path: "{{ ansible_user_dir }}/Backups"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  become: yes
  become_user: "{{ ansible_user_id }}"

