---
- name: Firewall | configure zone interface
  firewalld:
      zone: FedoraServer
      source: 10.0.0.0/24
      interface: "{{ ansible_default_ipv4.interface }}"
      state: enabled
      permanent: true
  notify:
    - reload firewall

- name: Firewall | configure zone port
  firewalld:
      zone: FedoraServer
      state: enabled
      port: "4445/udp"
      permanent: true
  notify:
    - reload firewall


- name: Firewall | configure zone services
  firewalld:
      zone: FedoraServer
      state: enabled
      permanent: true
      service: "{{ item }}"
  with_items:
    - ssh
    - mdns
    - dhcpv6-client
    - ipp
    - ipp-client
    - pulseaudio
    - snmp
    - nfs
    - mountd
    - rpc-bind
    - samba-client
  notify:
    - reload firewall
