---
- name: Firewall | install
  dnf: 
    name: firewalld
    state: latest

- name: Firewall | start enable
  systemd:
    name: firewalld
    state: started
    enabled: True

- name: Firewall | assign interface to zones
  firewalld:
    zone: "FedoraServer"
    interface: "{{ ansible_default_ipv4.interface }}"
    permanent: yes
    state: enabled

- name: Firewall | Create port rules for zones
  firewalld:
    zone: "FedoraServer"
    port: "{{ ports_dict.port }}"
    source: "{{ ports_dict.source }}"
    permanent: yes
    state: enabled

- name: Firewall | Create service rules for zones
  firewalld:
    zone: "FedoraServer"
    rich_rule: rule family="ipv4" source address="{{ standard_source }}" accept
    source: "{{ standard_source }}"
    permanent: yes
    state: enabled

- name: Firewall | Reload it
  command: firewall-cmd --reload
