- name: virt | install packages for bridge
  dnf:
    state: latest
    name: "{{ item }}"
  loop: ['policycoreutils-python-utils', 'podman', 'buildah', 'skopeo', 
    'cockpit', 'cockpit-podman', 'cockpit-bridge', 'cockpit-machines', 'cockpit-storaged', 'cockpit-system']
