---
- name: gaming | install negativo repos
  yum_repository:
      name: fedora-multimedia
      description: "negativo17 - Multimedia"
      baseurl: https://negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
      gpgcheck: no
      enabled: yes
  notify: update-all

  #- name: gaming | install negativo steam repos
  # dnf:
    #      state: latest
    #      name: "{{ item }}"
    #  with_items:
      #  - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-27.noarch.rpm'
      #  - 'https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-27.noarch.rpm'
      #  notify: update-all

- name: gaming | Install gaming packages
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - supertuxkart
  #  - 0ad
  #  - wesnoth
  - steam

    ## - name: gaming | add copr lsi
    ##   command: /usr/bin/dnf copr enable -y alunux/linux-steam-integration
    ##   dnf:
    ##       state: latest
    ##       name: linux-steam-integration
    ## TODO - Find out why this doesnt work

- name: gaming | Install generic gaming drivers
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - kernel-devel
  - kernel-headers
  - gcc
  - acpid
  - pkgconfig
  - mesa-vdpau-drivers.x86_64
  - mesa-vdpau-drivers.i686
  - vulkan.x86_64
  - vulkan.i686
  - xpad
  - mesa-vulkan-drivers
  - yarock
  notify:
    - add xpad module


- name: gaming | Install Radeon tools if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - radeontop
  - radeontool
  - libtxc_dxtn.i686
  - libtxc_dxtn.x86_64
  when: amd == true



  #- name: gaming | Install snaps
  # TODO

  #- name: gaming | Install flatpaks
  # TODO

  #- name: gaming | set up downloaded games from itch.io
