---
- name: gaming | Install generic gaming drivers
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - gcc
  - acpid
  - pkgconfig
  - mesa-vdpau-drivers.x86_64
  - mesa-vdpau-drivers.i686
  - vulkan.x86_64
  - vulkan.i686
  - xboxdrv
  - mesa-vulkan-drivers
  notify:
    - restart xboxdrv

'''
- name: gaming | Install Radeon tools if that variable is set
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - radeontop
  - radeontool
  - libtxc_dxtn.i686
  - libtxc_dxtn.x86_64
  when: amd == true



  #- name: gaming | Install snaps
  # TODO

  #- name: gaming | Install flatpaks
  # TODO

  #- name: gaming | set up downloaded games from itch.io
'''
