---
- name: install a few normal things
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - tilix
    - vim
    - syncthing

- name: make vim right
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: start up user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
    scope: user
  become_user: zach
  loop:
    - syncthing
    - podman.socket
    - podman-auto-update.service

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become_user: zach

- name: install the flattened paks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  become_user: zach
  loop: 
    - com.getpostman.Postman
    - com.github.babluboy.bookworm
    - com.github.optyfr.JRomManager
    - com.mojang.Minecraft
    - com.valvesoftware.Steam
    - im.riot.Riot
    - com.obsproject.Studio
    - com.github.tchx84.Flatseal
    - com.github.johnfactotum.Foliate
    - de.haeckerfelix.Fragments
    - com.discordapp.Discord
    - com.github.unrud.VideoDownloader
    - org.jitsi.jitsi-meet
    - de.haeckerfelix.Shortwave
    - com.github.louis77.tuner
    - com.jetbrains.PyCharm-Community
    - im.riot.Riot
    - com.microsoft.Teams
    - org.gnome.Polari
    - edu.stanford.Almond
    - com.bitwarden.desktop
    - org.gnome.Firmware
    - org.gnome.seahorse.Application
