---
- name: Zach | create vim backup dir
  file:
    path: "{{ ansible_user_dir }}/.vim/tmp"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: Zach | create vim plugin dir
  file:
    path: "{{ ansible_user_dir }}/.vim/plugged"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755
  notify: install plugged

- name: Zach | create Code dir
  file:
    path: "{{ ansible_user_dir }}/Code"
    state: directory
    mode: 0755

- name: Zach | minidlna
  dnf:
    name: minidlna
    state: latest
  become: yes
  become_user: root

<<<<<<< HEAD
- name: Zach | add copr_s
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
    seuser: _default
    serole: _default
    setype: _default
  with_items:
    - _copr_dagostinelli-prestopalette.repo
    - _copr_tetradecahedron-Newsboat.repo
    - _copr_thelocehiliosan-yadm.repo
  become: yes
  become_user: root
  notify:
    - update pkgs

- name: Zach | install the copr_s
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
#    - yadm
    - prestopalette
    - newsboat
    - gnome-tweak-tool
  become: yes
  become_user: root
=======
  # name: Zach | add copr_s
  # copy:
  #   src: "{{ item }}"
  #   dest: "/etc/yum.repos.d/{{ item }}"
  #   owner: root
  #   group: root
  #   mode: 0644
  #   seuser: _default
  #   serole: _default
  #   setype: _default
  # with_items:
  #   - _copr_dagostinelli-prestopalette.repo
  # become: yes
  # become_user: root
  # notify:
  #   - update pkgs
  #
  # name: Zach | install the copr_s
  # dnf:
  #   name: "{{ item }}"
  #   state: latest
  # with_items:
  #   - prestopalette
  #   - gnome-tweak-tool
  # become: yes
  # become_user: root
>>>>>>> devel
