---
- name: Zach | create vim backup dir
  file:
    path: "/home/{{ home_dir_user }}/.vim/tmp"
    state: directory
    owner: "{{ home_dir_user }}"
    group: "{{ home_dir_user }}"
    mode: 0755
  become: yes
  become_user: "{{ home_dir_user }}"

- name: Zach | create vim plugin dir
  file:
    path: "/home/{{ home_dir_user }}/.vim/tmp"
    state: directory
    owner: "{{ home_dir_user }}"
    group: "{{ home_dir_user }}"
    mode: 0755
  notify: install plugged
  become: yes
  become_user: "{{ home_dir_user }}"

- name: Zach | create Code dir
  file:
    path: "/home/{{ home_dir_user }}/Code"
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ home_dir_user }}"

- name: Zach | Do the Doooots
  copy:
    src: "{{ item }}"
    dest: "/home/{{ home_dir_user}}/{{ item }}"
    owner: "{{ home_dir_user }}"
    group: "{{ home_dir_user }}"
    decrypt: yes
  with_items:
  - .gnupg
  - .task
  - .vim
  - .bash_profile
  - .gitconfig
  - .pagureconfig
  - .restic_info
  - .taskrc
  - .vimrc
  become: yes
  become_user: "{{ home_dir_user }}"


