---
- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become_user: zach

- name: install the flattened paks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  become_user: zach
  loop: 
    - com.getpostman.Postman
    - com.github.babluboy.bookworm
    - com.github.optyfr.JRomManager
    - com.leinardi.gwe
    - com.mojang.Minecraft
    - com.spotify.Client
    - com.valvesoftware.Steam
    - im.riot.Riot
    - org.gnome.Music
    - org.telegram.desktop
