---
- name: Restic  | Install restic packages
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
  - restic
  - python2-scp
  - python3-scp
  - python3-paramiko
  - python3-dnf-plugins-extras-common
  - python3-dnf-plugins-core
  - autofs
  become: True

- name: Restic | make sure /srv exists and is owned by user
  file:
    path: /srv/backups
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Restic | set up automounter
  copy:
    src: "{{ item }}"
    dest: /etc/
  with_items:
  - auto.master
  - auto.backups
  notify:
  - reload_autofs
  become: True
  
- name: copy exclude file
  copy:
    src: restic_excludes.txt
    dest: /srv/backups/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: copy restic pwd file
  copy:
    src: .restic_info
    dest: /srv/backups/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: copy cron.allow is important
  copy:
    src: cron.allow
    dest: /etc/cron.allow
    owner: root
    group: root
    mode: 0644    
  become: True
 
- name: schedule backups
  cron:
    name: homedirbackup
    hour: 22
    minute: "{{ host_backup_time }}"
    job: restic -r /srv/backups backup /home/zach --exclude-file /srv/backups/restic_excludes --password-file=/srv/backups/.restic_info
  notify:
  - reload cron

- name: Restic | email snapshot list
  cron:
    name: reschecker
    hour: 22
    minute: 45
    job: python3 /home/zach/Python/reschecker/reschecker.py
  notify:
  - reload cron

- name: prune daily backups
  cron:
    name: prune snapshots with restic
    weekday: 0
    hour: 23
    minute: 45
    job: restic -r /srv/backups forget --keep-last 10 keep-weekly 4 --keep-monthly 3 --keep-yearly 1 --prune --password-file=/srv/backups/.restic_info 
  when: ansible_host == "tori.tsundoku.pw"
  notify:
  - reload cron
