---
- name: Common | Install common packages
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - vim-enhanced
  - tmux
  - inkscape
  - java-1.8.0-openjdk
  - youtube-dl
  - smartmontools
  - kernel-devel
  - dkms
  - deja-dup
  - python3-dnf-plugins-extras-common
  - NetworkManager-tui
  - python-firewall
  - python3-firewall

- name: Common | set up fstrim if ssdisk
  systemd:
    name: fstrim.timer
    state: started
    enabled: true
  when:
    ssdisk == true

- name: Common | install a few Qt apps if appropriate
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
  - kate
  - latte-dock
  when:
    qt == true

- name: Common | install Cups
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
  - cups
  - cups-lpd
  - cups-client
  - cups-pdf
  - cups-ipptool
  - gutenprint-cups

- name: Common | set etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

