---
- name: Common | Install common packages
  dnf:
      state: latest
      name: "{{ item }}"
  with_items:
  - weechat
  - inkscape
  - java-1.8.0-openjdk
  - smartmontools
  - NetworkManager-tui
  - python3-firewall
  - python3-dnf-plugins-core
  - python3-dnf-plugins-extras-common
  - python3-dnf-plugin-system-upgrade
  - dnf-automatic
  - python-dnf
  - libXScrnSaver
  - lsof
  - nfs-utils

- name: Common | set up fstrim if ssdisk
  systemd:
    name: fstrim.timer
    state: started
    enabled: true
  when:
    ssdisk == true

- name: Common | copy dnf-automatic files
  copy:
     src: dnf
     dest: /etc/dnf/
     owner: root
     group: root
     mode: 0644

- name: Common | activate dnf-automatic
  systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: true

- name: Common | Mount Mods from Oliver unless Oliver
  mount:
    path: "{ ansible_user_home_dir }/.minecraft/mods"
    src: ilum://home/oliver/.minecraft/mods
    fstype: nfs
    opts: _netdev
    state: mounted
  when: '"{ ansible_hostname }" != "ilum.grobble.lan"'
