---
- name: Common | Install common packages
  dnf:
      state: latest
      name: ['java-1.8.0-openjdk', 'smartmontools', 'python3-firewall', 'lsof',  
      'python3-dnf-plugins-core', 'python3-dnf-plugins-extras-common', 'vim',  
      'python3-dnf-plugin-system-upgrade', 'dnf-automatic', 'libXScrnSaver',  
      'nfs-utils', 'sysstat', 'vim-X11', 'syncthing']

- name: Common | set up fstrim if ssdisk
  systemd:
    name: fstrim.timer
    state: started
    enabled: true

- name: Common | copy dnf-automatic files
  copy:
     src: dnf
     dest: /etc/dnf/
     owner: root
     group: root
     mode: 0644

- name: Common | activate dnf-automatic
  systemd:
    name: dnf-automatic-install.timer
    state: started
    enabled: true

- name: Common | start syncthing as user
  systemd:
    name: syncthing
    state: started
    enabled: true
    scope: user
  become: True
  become_user: 'zach'
