#file - common role tasks main.yml
---
- name: Common | set up fstrim if ssdisk
  systemd:
    name: fstrim.timer
    state: started
    enabled: true
  when:
    ssdisk == true
    
    #- name: Common | copy pub ssh keys
    #  authorized_key:
      #    user: "{{ user }}"
      #    state: present
      #    key: "{{ item }}"
      #  with_file:
        #    - key_vault/ansible/id_ecdsa.pub
        #    - key_vault/jebel_krong/id_ecdsa.pub
        #    - key_vault/jkrong/id_ecdsa.pub
        #  when: isdesktop == true

  #- name: Common | copy private ssh key to owner
  #  copy:
    #   src: "key_vault/{{ user }}/id_ecdsa"
    #   dest: "{{ homedir }}/.ssh/"
    #   owner: "{{ user }}"
    #   group: "{{ user }}"
    #    mode: 0600
    #  when: isdesktop == true

- name: Common | copy sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600

- name: Common | set etc/hosts
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
