- name: virt-net | install the req packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - python3-networkmanager
    - nm-connection-editor
    - glib-networking
    - NetworkManager-libnm
    - python3-libnmstate

- name: virt-net | create a bridge
  nmcli:
    type: bridge
    conn_name: 'br0'
    ip4: '10.23.19.91'
    gw4: '10.23.19.1'
    dns4:
      - '10.23.19.51'
      - '1.1.1.1'
      - '8.8.8.8'
    dns4_search:
      - 'segfawlty.space'
    state: present

- name: virt-net | config if for bridge support
  nmcli:
    type: bridge-slave
    conn_name: "br-{{ item }}"
    ifname: "{{ item }}"
    master: 'br0'
    state: present
    loop: "{{ ansible_interfaces[:2] }}"
