- name: virt-net | copy the files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: '10-bridge.netdev', dest: '/etc/systemd/network/10-bridge.netdev' }
    - { src: '20-wired.network', dest: '/etc/systemd/network/20-wired.network' }
    - { src: '30-bridge.network', dest: '/etc/systemd/network/30-bridge.network' }

- name: virt-net | enable start systemd-networkd
  systemd:
    name: systemd-networkd
    state: started
    enabled: True

- name: virt-net | disable stop NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: False
