- name: podman for zach setup | with priv
  hosts: kujira.segfawlty.space
  become: yes
  connection: local
  vars:
    stor_vg: 'vault'
    stor_lv: 'pod_storage'
    stor_size: '200G'
    stor_tp: 'v_thnpool'
    runt_tp: 'flsh'
    runt_vg: 'ssd'
    tp_size: '110G'
    runt_lv: 'pod_run'
    runt_size: '50G'
  roles:
    - podman

