- name: mc server setup
  hosts: mc.wefartin.space
  become: yes
  vars:
    server_dirs: 
    - 'bear'
    - 'goat'
    version_target: '1.15.1'
  tasks:
    - name: download the newest paper
      get_url: 
        url: "https://papermc.io/api/v1/paper/{{ version_target }}/latest/download"
        dest: "/srv/{{ item }}/server.jar"
        force: yes
        backup: yes
        owner: zach
        group: zach
      loop: "{{ server_dirs }}"
    
    - name: stop the servers
      systemd:
        name: "{{ item }}"
        state: stopped
      loop: 
      - 'paper_bear'
      - 'paper_goat'

    - name: restart the servers
      systemd:
        name: "{{ item }}"
        state: started
        daemon-reload: yes
      loop: 
      - 'paper_bear'
      - 'paper_goat'
