- name: reload cron
  systemd:
    name: crond 
    enabled: yes
    state: restarted
  become: True

- name: reload_autofs
  systemd:
    name: autofs
    enabled: yes
    state: restarted
  become: True
 
